baseURL = 'https://linh.nguyen.be'
languageCode = 'en'
title = "linh's journal"
theme = 'typo'
capitalizeListTitles = false
disableHugoGeneratorInject = true

[taxonomies]
tag = 'tags'

[params]
description = "A place to share my thoughts and ideas."
theme = 'auto'
colorPalette = 'base16-ocean'
hideHeader = false
showFooter = false
footerContent = "have some thoughts? contact me at <a href='mailto:linh@nguyen.be'>linh@nguyen.be</a>"

homeIntroTitle = ''
homeIntroContent = """
"""
homeCollectionTitle = ''
homeCollection = 'articles'

paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

[params.breadcrumbs]
enabled = false

[[params.menu]]
name = "articles"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[markup]
[markup.highlight]
style = 'algol_nu'

[params.giscus]
enable = true
repo = "linh-n/blog"
repoid = "R_kgDOOdJ5-g"
category = "Announcements"
categoryid = "DIC_kwDOOdJ5-s4CpWrZ"
mapping = "pathname"
theme = "preferred_color_scheme"
