baseURL = 'https://linh.nguyen.be'
languageCode = 'en-us'
title = "linh's journal"
theme = 'typo'

[taxonomies]
tag = 'tags'


[params]
description = "A place to share my thoughts and ideas."
theme = 'auto'
colorPalette = 'base16-ocean'
hideHeader = false
showFooter = true
footerContent = "have some thoughts? contact me at <a href='mailto:linh@nguyen.be'>linh@nguyen.be</a>"

# Intro on main page, content is markdown
homeIntroTitle = ''
homeIntroContent = """
"""
# Collection to display on home
homeCollectionTitle = ''
homeCollection = 'resources'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = false

# Main menu pages
[[params.menu]]
name = "resources"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol_nu'
