name: Deploy
on: 
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          command: >
            pages deploy public --project-name=blog
            ${{ github.ref == 'refs/heads/dev' && '--branch=dev' || '' }}

      - name: Get changed content files
        id: changed_files
        run: |
          # Set base URL based on branch
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            BASE_URL="https://dev.nguyen.be"
          else
            BASE_URL="https://linh.nguyen.be"
          fi

          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^content/' || true)

          urls=""
          root_included=false

          while IFS= read -r file; do
            # Strip prefix and extension
            path=${file#content/}
            path_no_ext=${path%%.*}
            dirname=$(dirname "$path_no_ext")
            basename=$(basename "$path_no_ext")

            # Only add if path is non-empty
            if [[ -n "$path" ]]; then
              urls="${urls}\"$BASE_URL/\","
              urls="${urls}\"$BASE_URL/sitemap.xml\","
            fi

            # Handle about.md → /about
            if [[ "$basename" == "index" || "$basename" == "_index" ]]; then
              clean_path="$BASE_URL/$dirname"
            else
              clean_path="$BASE_URL/$path_no_ext"
            fi

            urls="${urls}\"$clean_path\","
          done <<< "$changed"

          urls="[${urls%,}]"

          echo "CHANGED_PATHS=$urls" >> $GITHUB_OUTPUT

          echo "🧹 Purging the following URLs:"
          echo "$urls"          

      - name: Cache purge
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: ${{ steps.changed_files.outputs.CHANGED_PATHS }}
